FROM python:3.9
RUN apt update &&\
    apt install build-essential -y &&\
    apt update &&\
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&\
    python3.9 get-pip.py &&\
    pip install --upgrade pip &&\
    sudo apt-get install -y python3-pip git libtinfo-dev libzmq3-dev libcairo2-dev libpango1.0-dev libmagic-dev libblas-dev liblapack-dev &&\
    curl -sSL https://get.haskellstack.org/ | sh &&\
    git clone https://github.com/gibiansky/IHaskell &&\
    cd IHaskell &&\
    pip3 install -r requirements.txt &&\
    stack install --fast &&\
    ihaskell install --stack &&\
    chmod +x ./docker/entrypoint.sh
EXPOSE 10000
ENTRYPOINT ["./docker/entrypoint.sh"]